
name: mcgPipeline

stages:
  - stage: Stage_1
    displayName: Initialize
    condition: alsway()
    jobs:
      - job: job_1
        steps:
          - script: echo Job 1
  - stage: Stage_2
    displayName: After configuration
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))