
name: mcgPipeline

stages:
  - stage: Stage_1
    displayName: Initialize
    condition: alsway()
    jobs:
      - job: job_1
        steps:
          - script: echo Job 1
  - stage: Stage_2
    displayName: After configuration
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - stage: Deploy
    jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      pool:
        vmImage: 'Ubuntu-latest'
      # creates an environment if it doesn't exist
      environment: 'Develop'
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Hello world